### ISSUE TITLE
A few improvements for week7 workshop and practice

### ISSUE THREAD

**Issue by jsun969** [ht-timchen/UA-CS1015#1]
Hi Tim, I'm an IAP student. Here are some improvements I found when doing week7 workshop and practice.

1. In the workshop calculator exercise, the layout has a little issue:
![CleanShot 2024-04-25 at 18 41 28@2x](https://github.com/ht-timchen/UA-CS1015/assets/29330847/9bc89fd9-280b-4a34-ba7f-52d82d59364d)

IMHO, it should be:
```py
btn = tk.Button(..., width=6) # `width` should be added here
btn.grid(row=4, column=0, columnspan=2)
btn.bind("<Button-1>", on_btn_click)

btn = tk.Button(master=win, text="=") # Remove `width=5`
btn.grid(row=4, column=2)
```

2. The `calc` function block should appeared before the layout block for using this function. IMHO, [eval](https://docs.python.org/3/library/functions.html#eval) can be an alternative for `calc` function so that this exercise can be more simple.

3. I saw many `bnt` in the code, is it a typo? Because the abbreviation of `button` could be `btn`.

Happy to send a PR for them!

**Comment by ht-timchen** [comment]
ah, I am no longer updating the workshop content; could you let the course coordinator know?

**Comment by jsun969** [comment]
Alr, thx for the reply.
